#define HOLD_ON_OTHER_KEY_PRESS
#define RETRO_TAPPING
#define TAPPING_TERM 300

#define COMBO_TERM 20
#define EXTRA_SHORT_COMBOS
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_SHOULD_TRIGGER

#define FORCE_NKRO
